#spring下面的相关配置
spring:
  profiles:
    active: dev
    #active: pro


  #数据源配置
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=blog1
    username: sa
    password: 17931
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver



  #配置thymeleaf模版
  thymeleaf:
      #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
      mode: HTML5
      #编码 可不用配置
      encoding: UTF-8
      #开发配置为false,避免修改模板还要重启服务器
      cache: false
      #配置模板路径，默认是templates，可以不用配置
      prefix: classpath:/templates/

  cache:
      type: ehcache




#tomcat相关配置
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /blog


#mybatis相关配置
mybatis:
  mapper-locations: classpath:mapper/*.xml #xml文件所在目录
  type-aliases-package: com.xp.blog.entity #取别名 配置完之后 可以直接在xml里面写类名即可，不用写全路径


# 配置pagehelper参数
pagehelper:
    helperDialect: sqlserver
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


